### ISSUE TITLE
Unable to uninstall node-alsa on x86

### ISSUE THREAD

**Issue by DrCWO** [xdissent/node-alsa#5]
This Repositiory seems to be broken. Last Update seven years ago. Here my issue:

npm install git+https://github.com/xdissent/node-alsa.git --save

> alsa@0.0.2 install /data/INTERNAL/device/node_modules/alsa
> node-gyp rebuild

make: Entering directory '/data/INTERNAL/device/node_modules/alsa/build'
  CXX(target) Release/obj.target/alsa/alsa.o
In file included from ../alsa.cc:3:0:
../pcm.h:16:31: error: expected class-name before '{' token
 class Pcm : public ObjectWrap {
                               ^
../pcm.h:48:5: error: 'uv_work_t' does not name a type
     uv_work_t request;
     ^
../pcm.h:100:34: error: 'Arguments' does not name a type
   static Handle<Value> New(const Arguments& args);
                                  ^
../pcm.h:101:35: error: 'Arguments' does not name a type
   static Handle<Value> Open(const Arguments& args);
                                   ^
../pcm.h:102:36: error: 'Arguments' does not name a type
   static Handle<Value> Close(const Arguments& args);
                                    ^
../pcm.h:103:35: error: 'Arguments' does not name a type
   static Handle<Value> Read(const Arguments& args);
                                   ^
../pcm.h:104:36: error: 'Arguments' does not name a type
   static Handle<Value> Write(const Arguments& args);
                                    ^
../pcm.h:106:62: error: 'AccessorInfo' does not name a type
   static Handle<Value> OpenedGetter(Local<String> str, const AccessorInfo& accessor);
                                                              ^
../pcm.h:107:64: error: 'AccessorInfo' does not name a type
   static Handle<Value> ReadableGetter(Local<String> str, const AccessorInfo& accessor);
                                                                ^
../pcm.h:108:64: error: 'AccessorInfo' does not name a type
   static Handle<Value> WritableGetter(Local<String> str, const AccessorInfo& accessor);
                                                                ^
../pcm.h:111:22: error: 'uv_work_t' has not been declared
   static void DoRead(uv_work_t* req);
                      ^
../pcm.h:112:25: error: 'uv_work_t' has not been declared
   static void AfterRead(uv_work_t* req);
                         ^
../pcm.h:115:23: error: 'uv_work_t' has not been declared
   static void DoClose(uv_work_t* req);
                       ^
../pcm.h:116:26: error: 'uv_work_t' has not been declared
   static void AfterClose(uv_work_t* req);
                          ^
../pcm.h:119:23: error: 'uv_work_t' has not been declared
   static void DoWrite(uv_work_t* req);
                       ^
../pcm.h:120:26: error: 'uv_work_t' has not been declared
   static void AfterWrite(uv_work_t* req);
                          ^
../pcm.h: In constructor 'alsa::Pcm::Pcm()':
../pcm.h:21:11: error: class 'alsa::Pcm' does not have any field named 'ObjectWrap'
   Pcm() : ObjectWrap(),
           ^
../pcm.h: In constructor 'alsa::Pcm::Baton::Baton(alsa::Pcm*, v8::Handle<v8::Function>)':
../pcm.h:54:12: error: 'class alsa::Pcm' has no member named 'Ref'
       pcm->Ref();
            ^
../pcm.h:55:7: error: 'request' was not declared in this scope
       request.data = this;
       ^
../pcm.h:56:47: error: no matching function for call to 'v8::Persistent<v8::Function>::New(v8::Handle<v8::Function>&)'
       callback = Persistent<Function>::New(cb_);
                                               ^
../pcm.h:56:47: note: candidate is:
In file included from /root/.node-gyp/8.11.1/include/node/node.h:63:0,
                 from ../alsa.cc:1:
/root/.node-gyp/8.11.1/include/node/v8.h:9167:4: note: static T* v8::PersistentBase<T>::New(v8::Isolate*, T*) [with T = v8::Function]
 T* PersistentBase<T>::New(Isolate* isolate, T* that) {
    ^
/root/.node-gyp/8.11.1/include/node/v8.h:9167:4: note:   candidate expects 2 arguments, 1 provided
In file included from ../alsa.cc:3:0:
../pcm.h: In destructor 'virtual alsa::Pcm::Baton::~Baton()':
../pcm.h:59:12: error: 'class alsa::Pcm' has no member named 'Unref'
       pcm->Unref();
            ^
../pcm.h:60:16: error: 'class v8::Persistent<v8::Function>' has no member named 'Dispose'
       callback.Dispose();
                ^
alsa.target.mk:92: recipe for target 'Release/obj.target/alsa/alsa.o' failed
make: *** [Release/obj.target/alsa/alsa.o] Error 1
make: Leaving directory '/data/INTERNAL/device/node_modules/alsa/build'
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:258:23)
gyp ERR! stack     at emitTwo (events.js:126:13)
gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
gyp ERR! System Linux 3.18.25
gyp ERR! command "/bin/node" "/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /data/INTERNAL/device/node_modules/alsa
gyp ERR! node -v v8.11.1
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
npm WARN ws@7.3.1 requires a peer of utf-8-validate@^5.0.2 but none is installed. You must install peer dependencies yourself.
npm WARN audiovolver-pro@1.0.0 No repository field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! alsa@0.0.2 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the alsa@0.0.2 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2020-08-21T07_05_33_027Z-debug.log

**Comment by spaceneedle** [comment]
Build also fails on armv7l (Raspberry Pi 4) in the same, exact way.
